scheduler:
  timezone: 'Europe/Berlin'

persistence:
  path: 'data/state.json'

modules:

  mymodule:
    enabled: false
    class: 'alarmclock.modules.mymodule.mymodule:MyModule'

  sound:
    enabled: false
    device: '/dev/audio'

  light:
    enabled: false
    gpio_pin: 17
    brightness: 100

  webui:
    enabled: true
    class: 'alarmclock.modules.webui.webui:WebUIModule'
    host: '0.0.0.0'
    port: 5000