core:
  scheduler:
    snooze: 8
    timezone: Europe/Berlin
  webui:
    color_profile: sunrise
    custom_accent: '#000000'
    custom_accent_strong: '#000000'
    enabled: true
    host: 0.0.0.0
    password: pass
    port: 5000
module:
  led:
    actions:
      click: ignore
      double_click: ignore
      long_press: ignore
      multi_click: ignore
      press: ignore
      release: ignore
    pin: 0
